services:
  api:
    build:
      context: ./api/
      target: dev
    ports:
      - 8000:80
    volumes:
      - ./api:/src
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080'
  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: secret*12345
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/secrets:/var/opt/mssql/secrets
  vue:
    build:
        context: ./vue
    ports:
        - 8080:8080
    env_file:
        - ./vue/.env.development
    volumes:
        - ./vue/:/opt/app
        # - node_modules:/opt/node_modules
    user: node
    tty: true